### ISSUE TITLE
No module named 'cli'

### ISSUE THREAD

**Issue by davidthewatson** [jaidevd/pyticks#33]
I'm running pyticks on python 3.5.1 on Mac OS X 10.11. I ran with the username and password according to the readme after installing requirements from pip. This is what I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyticks", line 9, in <module>
    load_entry_point('pyticks==0.0.1', 'console_scripts', 'pyticks')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'cli'
```

**Comment by jaidevd** [comment]
Thanks for pointing this out, @davidthewatson. There's no Python 3.5 support as of now, but that shouldn't be too difficult to add. Please check back in a couple of days.

**Comment by davidthewatson** [comment]
Thanks, I'll switch back to 2.7 for now. I didn't realize the 3.5 wasn't there until I tried to import some of those deps into 3.5.

**Comment by jaidevd** [comment]
@davidthewatson It should work with Python 3.5.1 (osx) as of the last commit. Please give it a shot. Also note that the requirements.txt has changed. You'll need to install six.
Thanks

**Comment by davidthewatson** [comment]
I just grabbed the clone on python 2.7.10 mac os x 10.10 and it doesn't work there either:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyticks", line 9, in <module>
    load_entry_point('pyticks==0.0.1', 'console_scripts', 'pyticks')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named pyticks_cli
```

**Comment by jaidevd** [comment]
@davidthewatson I think I made quite a few mistakes with setuptools. I always use `python setup.py develop` and therefore these bugs didn't come up sooner. Anyway, please update to the latest commit and let me know if it works. This should be fixed in both Python 2 and 3.
